/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.digiroots.main;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import com.digiroots.training.graph.OrigamiShape;
import com.digiroots.training.graph.OrigamiSurfaceAttributes;

/**
 *
 * @author khaddam
 */
public class SurfaceEditor extends javax.swing.JPanel {

    int surfaceNumber = 1;
    OrigamiShape shape;
    OrigamiSurfaceAttributes surface = null;
    /**
     * Creates new form SurfaceEditor
     */
    public SurfaceEditor() {
        initComponents();
    }

    public void init(OrigamiShape shape, String title, int surfaceNumber) {        
        this.shape=shape;
        this.surfaceNumber = surfaceNumber;
        lblTitle.setText(title);
        if (surfaceNumber==2)
            txtId.setEnabled(false);        
        txtId.getDocument().addDocumentListener(new DocumentListener() {
          public void changedUpdate(DocumentEvent e) {
            warn();
          }
          public void removeUpdate(DocumentEvent e) {
            warn();
          }
          public void insertUpdate(DocumentEvent e) {
            warn();
          }
          public void warn() {
              if (txtId.getText().isEmpty())
                  return;
              surface.id = txtId.getText();
              surface.applyAttributes();
          }
        });        
    }

    void refresh() {
        if (surfaceNumber == 1 && shape.selectedSurface1!=null)
            surface = shape.surfaceAttributeMap.get(shape.selectedSurface1);
        if (surfaceNumber == 2 && shape.selectedSurface2!=null)
            surface = shape.surfaceAttributeMap.get(shape.selectedSurface2);
        bindGUI();
    }

    private void bindGUI() {
        if (surface==null)
            return;
        txtId.setText(surface.id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitle.setText("Selected Surface");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTitle)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
