/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.digiroots.foldale.gui.paperbrowser;

import javax.swing.text.html.HTMLDocument;

/**
 *
 * @author khaddam
 */
public class ScientificPaperBrowserOld extends javax.swing.JFrame {

    /**
     * Creates new form ScientificPaperBrowser
     */
    public ScientificPaperBrowserOld() {
        initComponents();
        /*editor.setContentType( "text/html" );    
        String htmlString = "<html>\n"
                          + "<body>\n"
                          + "<h1>Welcome!</h1>\n"
                          + "<h2>This is an H2 header</h2>\n"
                          + "<p>This is some sample text</p>\n"
                          + "<p><a href=\"http://devdaily.com/blog/\">devdaily blog</a></p>\n"
                          + "</body>\n";
        editor.setText(htmlString);
        */
        pageBrowser.setPage("file:///C:/OrigamiProjects/p4.html");
        pageBrowser.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toc1 = new com.digiroots.foldale.gui.paperbrowser.Toc();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        abstract1 = new com.digiroots.foldale.gui.paperbrowser.Abstract();
        toc2 = new com.digiroots.foldale.gui.paperbrowser.Toc();
        jPanel1 = new javax.swing.JPanel();
        pageBrowser = new com.digiroots.foldale.gui.paperbrowser.WebBrowserPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setText("<html>\r\n  <head>\r\n    <style type=\"text/css\">\r\n      <!--\r\n        #header { font-weight: normal; font-size: 16pt }\r\n        #authors { font-size: 12pt }\r\n        #hearer { font-weight: bold }\r\n      -->\r\n    </style>\r\n    \r\n  </head>\r\n  <body>\r\n\n\r\n    <html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n      <head>\r\n        <style type=\"text/css\">\r\n          <!--\r\n            #header { font-weight: normal; font-size: 16pt }\r\n            #authors { font-size: 12pt }\r\n            #hearer { font-weight: bold }\r\n          -->\r\n        </style>\r\n        <meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=utf-8\">\r\n        <title>c:\\OrigamiProjects\\header</title>\r\n        \r\n      </head>\r\n      <body>\r\n        <p align=\"center\">\r\n          <b><span id=\"header\"><font face=\"Arial\">Similating Foldable User \r\n          Interfaces Using Origami</font></span></b>\r\n        </p>\r\n        <p align=\"center\">\r\n          <b><span id=\"authors\"><font face=\"Times New Roman\">Iyad \r\n          Khaddam&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Jean Vanderdonckt</font></span></b>\r\n        </p>\r\n        <p align=\"center\">\r\n          <b><span><font face=\"Times New Roman\">Universit&#233; catholique de \r\n          Louvain<br>B-1348 Louvain-la-Neuve (Belgium)<br>E-mails<br><br></font></span></b>\r\n        </p>\r\n      </body>\r\n    </html>\r\n  </body>\r\n</html>\r\n");
        try {
            jEditorPane1.setPage(new java.net.URL("file:/C:/OrigamiProjects/header.html"));
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout pageBrowserLayout = new javax.swing.GroupLayout(pageBrowser);
        pageBrowser.setLayout(pageBrowserLayout);
        pageBrowserLayout.setHorizontalGroup(
            pageBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        pageBrowserLayout.setVerticalGroup(
            pageBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pageBrowser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pageBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abstract1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(abstract1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificPaperBrowserOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificPaperBrowserOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificPaperBrowserOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificPaperBrowserOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificPaperBrowserOld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.digiroots.foldale.gui.paperbrowser.Abstract abstract1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.digiroots.foldale.gui.paperbrowser.WebBrowserPanel pageBrowser;
    private com.digiroots.foldale.gui.paperbrowser.Toc toc1;
    private com.digiroots.foldale.gui.paperbrowser.Toc toc2;
    // End of variables declaration//GEN-END:variables
}
